// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

// Exports
export {
	initWindowStore,
	disposeWindowStore,
	getWindowDesktop,
	getWindowVersion,
	isWindowStoreInitialized,
} from './windowStore';

// Types
export type {IWindowStoreState} from './windowStore';
