// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

// Exports
export {useWindow} from './useWindow';

// Types
export type {IWindowState} from './useWindow';
