// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

// Exports
export { GameDataManager } from './GameDataManager';
export { FurnitureType } from './IGameDataManager';

// Types
export type { GameDataEvents } from './GameDataManager';
export type { 
  IFurnitureData,
  IEffectData,
  IProductData,
  IFigureSetData,
  IFigurePartData,
  IFigureMapData,
  IFigureMapLibrary,
  IFigureMapPart,
  IGameDataManager,
  IGameDataUrls,
 } from './IGameDataManager';
