// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

// Types
export type { IWindow } from './IWindow';
export type { IWindowContainer } from './IWindowContainer';
