// Auto-generated barrel file — do not edit manually
// Generated by Barrel Index Generator

export {RoomObjectAvatarCarryObjectUpdateMessage} from './RoomObjectAvatarCarryObjectUpdateMessage';
export {RoomObjectAvatarChatUpdateMessage} from './RoomObjectAvatarChatUpdateMessage';
export {RoomObjectAvatarDanceUpdateMessage} from './RoomObjectAvatarDanceUpdateMessage';
export {RoomObjectAvatarDirectionUpdateMessage} from './RoomObjectAvatarDirectionUpdateMessage';
export {RoomObjectAvatarEffectUpdateMessage} from './RoomObjectAvatarEffectUpdateMessage';
export {RoomObjectAvatarExperienceUpdateMessage} from './RoomObjectAvatarExperienceUpdateMessage';
export {RoomObjectAvatarExpressionUpdateMessage} from './RoomObjectAvatarExpressionUpdateMessage';
export {RoomObjectAvatarFigureUpdateMessage} from './RoomObjectAvatarFigureUpdateMessage';
export {RoomObjectAvatarFlatControlUpdateMessage} from './RoomObjectAvatarFlatControlUpdateMessage';
export {RoomObjectAvatarGestureUpdateMessage} from './RoomObjectAvatarGestureUpdateMessage';
export {RoomObjectAvatarGuideStatusUpdateMessage} from './RoomObjectAvatarGuideStatusUpdateMessage';
export {RoomObjectAvatarMutedUpdateMessage} from './RoomObjectAvatarMutedUpdateMessage';
export {RoomObjectAvatarOwnMessage} from './RoomObjectAvatarOwnMessage';
export {RoomObjectAvatarPetGestureUpdateMessage} from './RoomObjectAvatarPetGestureUpdateMessage';
export {RoomObjectAvatarPlayerValueUpdateMessage} from './RoomObjectAvatarPlayerValueUpdateMessage';
export {RoomObjectAvatarPlayingGameMessage} from './RoomObjectAvatarPlayingGameMessage';
export {RoomObjectAvatarPostureUpdateMessage} from './RoomObjectAvatarPostureUpdateMessage';
export {RoomObjectAvatarSelectedMessage} from './RoomObjectAvatarSelectedMessage';
export {RoomObjectAvatarSignUpdateMessage} from './RoomObjectAvatarSignUpdateMessage';
export {RoomObjectAvatarSleepUpdateMessage} from './RoomObjectAvatarSleepUpdateMessage';
export {RoomObjectAvatarTypingUpdateMessage} from './RoomObjectAvatarTypingUpdateMessage';
export {RoomObjectAvatarUpdateMessage} from './RoomObjectAvatarUpdateMessage';
export {RoomObjectAvatarUseObjectUpdateMessage} from './RoomObjectAvatarUseObjectUpdateMessage';
export {RoomObjectDataUpdateMessage} from './RoomObjectDataUpdateMessage';
export {RoomObjectHeightUpdateMessage} from './RoomObjectHeightUpdateMessage';
export {RoomObjectMoveUpdateMessage} from './RoomObjectMoveUpdateMessage';
export {RoomObjectUpdateStateMessage} from './RoomObjectUpdateStateMessage';
